[package]
name = "pdf-folio-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
blake3.workspace = true
chrono.workspace = true
directories.workspace = true
pdf-folio-db = { path = "../pdf-folio-db" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
url.workspace = true
webbrowser.workspace = true
