[package]
name = "pdf-folio-ui-components"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
iced.workspace = true
pdf-folio-core = { path = "../pdf-folio-core" }
pdf-folio-db = { path = "../pdf-folio-db" }
pdf-folio-style = { path = "../pdf-folio-style" }
