[package]
name = "pdf-folio-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
directories.workspace = true
iced.workspace = true
notify.workspace = true
pdf-folio-core = { path = "../pdf-folio-core" }
pdf-folio-db = { path = "../pdf-folio-db" }
pdf-folio-cloud = { path = "../pdf-folio-cloud" }
pdf-folio-style = { path = "../pdf-folio-style" }
pdf-folio-viewer = { path = "../pdf-folio-viewer" }
pdf-folio-ui-components = { path = "../pdf-folio-ui-components" }
reqwest.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
webbrowser.workspace = true
zip.workspace = true
